export const packages = [
  {
    name: "Mini Session",
    duration: "30 minutes",
    price: "$225",
    priceNote: "starting at",
    description: "Perfect for quick milestones, updated portraits, or seasonal shots.",
    features: [
      "30-minute outdoor session",
      "1 location",
      "Immediate family (up to 4 people)",
      "20+ edited digital images",
      "Online gallery delivery",
      "Delivered within 3–7 business days",
      "Print release included",
    ],
    highlight: false,
    cta: "Book Mini Session",
  },
  {
    name: "Standard Session",
    duration: "60 minutes",
    price: "$350",
    priceNote: "starting at",
    description: "Our most popular option — ideal for families, grads, and couples.",
    features: [
      "60-minute outdoor session",
      "Up to 2 locations",
      "Any group size",
      "40+ edited digital images",
      "Online gallery delivery",
      "Delivered within 3–7 business days",
      "Print release included",
      "1 outfit change welcome",
    ],
    highlight: true,
    cta: "Book Standard Session",
  },
  {
    name: "Event Coverage",
    duration: "Varies",
    price: "$900",
    priceNote: "starting at",
    description:
      "Full coverage for birthday parties, gender reveals, quinceañeras & more.",
    features: [
      "Up to 3 hours of coverage",
      "Full event documentation",
      "100+ edited images",
      "Online gallery delivery",
      "1-2 weeks turnaround",
      "Print release included",
      "Custom packages available",
    ],
    highlight: false,
    cta: "Get a Quote",
  },
];
